### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by hIASL99** [JeremyMahieu/angular-json-refs-interceptor#4]
When trying to use the interceptor with a token request an error occurs while deserialization.

**Comment by JeremyMahieu** [comment]
Thanks, can you paste the error text?

**Comment by hIASL99** [comment]
The error occurs when i try to get a token and its not a valid JSON:

SyntaxError: Unexpected token 'e', "eyJhbGciOi"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Function.resolveReferences (refs.interceptor.js:49:25)
    at refs.interceptor.js:109:43
    at map.js:10:37
    at OperatorSubscriber._this._next (OperatorSubscriber.js:33:21)
    at Subscriber.next (Subscriber.js:51:18)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183:16)
    at SafeSubscriber.next (Subscriber.js:122:22)
    at Subscriber._next (Subscriber.js:72:26)
    at Subscriber.next (Subscriber.js:49:18)
